[package]
name = "drawpanel-bind-wasm"
version = "0.0.0"
edition = "2021"
description = "Drawpanel wasm binder"
publish = true
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/drawpanel/drawpanel"
repository = "https://github.com/drawpanel/drawpanel.git"
keywords = ["drawpanel", "drawpanel-bind"]
categories = ["drawpanel", "drawpanel-bind"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
