[package]
name = "drawpanel-core"
version = "0.0.0"
edition = "2021"
description = "Drawpanel core"
publish = true
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/drawpanel/drawpanel"
repository = "https://github.com/drawpanel/drawpanel.git"
keywords = ["drawpanel", "draw"]
categories = ["drawpanel", "draw"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = {version = "0.23.0" }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
erased-serde = "0.3.23"

[dependencies.educe]
version = "0.4.20"
features = ["Default"]
default-features = false

[dev-dependencies]
mockall = "0.11.1"
