[package]
name = "drawpanel-bind-fltk"
version = "0.0.0"
edition = "2021"
description = "Drawpanel fltk binder"
publish = true
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/drawpanel/drawpanel"
repository = "https://github.com/drawpanel/drawpanel.git"
keywords = ["drawpanel", "drawpanel-bind"]
categories = ["drawpanel", "drawpanel-bind"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drawpanel-core = { path = "../drawpanel-core" }
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
geo = {version = "0.22.1" }
