[package]
name = "drawpanel"
version = "0.0.0"
edition = "2021"
authors = ["WumaCoder 1829913225@qq.com>"]
description = "A cross platform drawing tool."
publish = true
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/drawpanel/drawpanel"
repository = "https://github.com/drawpanel/drawpanel.git"
keywords = ["drawpanel", "draw"]
categories = ["desktop", "drawpanel", "draw"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drawpanel-core = { path = "../drawpanel-core" }
drawpanel-bind-fltk = { path = "../drawpanel-bind-fltk" }
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
geo = {version = "0.22.1" }

